### ISSUE TITLE
Exception when building region 8028

### ISSUE THREAD

**Issue by Jonatino** [rsmod/rsmod#3]
```
Exception in thread "DefaultDispatcher-worker-4" java.lang.IndexOutOfBoundsException: Index 41199 out of bounds for length 41120
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.rsmod.game.cache.ConfigTypeList.get(ConfigType.kt)
	at org.rsmod.plugins.api.cache.map.collision.CollisionMapLoader.loadCollision-iqjYmvk(CollisionMapLoader.kt:127)
	at org.rsmod.plugins.api.cache.map.collision.CollisionMapLoader.load-UzMyBeg(CollisionMapLoader.kt:44)
	at org.rsmod.plugins.api.cache.map.collision.CollisionMapLoader.load(CollisionMapLoader.kt:36)
	at org.rsmod.plugins.api.cache.map.collision.Collision_map_plugin$1.invoke(collision-map.plugin.kts:8)
	at org.rsmod.plugins.api.cache.map.collision.Collision_map_plugin$1.invoke(collision-map.plugin.kts:3)
	at org.rsmod.plugins.api.cache.map.xtea.loader.XteaFileLoader.load(XteaFileLoader.kt:74)
	at org.rsmod.plugins.api.cache.map.xtea.loader.Xtea_loader_plugin$1.invoke(xtea-loader.plugin.kts:9)
	at org.rsmod.plugins.api.cache.map.xtea.loader.Xtea_loader_plugin$1.invoke(xtea-loader.plugin.kts:3)
	at org.rsmod.game.task.StartupTaskKt$launchNonBlocking$1$ioJob$1$1$1.invokeSuspend(StartupTask.kt:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[INFO] Feb 20, 2021 16:38:22 PM [main] Server$startup$1 invokeSuspend
 Loaded 16 plugin(s)
[INFO] Feb 20, 2021 16:38:22 PM [main] Server$startup$1 invokeSuspend
 Game listening to connections on port 54900

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

Noticed some regions have object id's larger than the definition count.

**Comment by Tomm0017** [comment]
Addressed in commit https://github.com/rsmod/rsmod/commit/6806520a3747167dc331cc306726164c97a492e1
